# Created with package:mono_repo v1.2.1
language: dart

sudo: required
jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: src - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
      env: PKG="src"
      dart: dev
    - stage: analyzer_and_format_stable
      name: "SDK: stable - DIR: src - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
      env: PKG="src"
      dart: stable
    - stage: unit_test
      name: "SDK: stable - DIR: src - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="src"
      dart: stable
    - stage: unit_test
      name: "SDK: 2.0.0 - DIR: src - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="src"
      dart: "2.0.0"
    - stage: unit_test
      name: "SDK: dev - DIR: src - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="src"
      dart: dev
    - stage: test_coverage
      name: "SDK: stable - DIR: src - TASKS: pub run test_coverage"
      before_script: 
        - pub global activate coverage
      script: ./tool/travis_codecov.sh src
      after_success: bash <(curl -s https://codecov.io/bash) -f lcov.info
      env: PKG="src"
      dart: stable

stages:
  - analyzer_and_format
  - analyzer_and_format_stable
  - unit_test
  - test_coverage

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
